name: Build and Deploy to Azure Kubernetes Service

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:

env:
  AKS_CLUSTER_NAME: rgweatheraks
  RESOURCE_GROUP: weather

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore ./WeatherApi.csproj

    - name: Build
      run: dotnet build ./WeatherApi.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./WeatherApi.csproj -c Release -o ./publish

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry (ACR)
      run: |
        az acr login --name ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER }}/weatherapi:${{ github.sha }} .
        docker push ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER }}/weatherapi:${{ github.sha }}

    - name: Set AKS Context
      run: |
        az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}

    - name: Create Kubernetes Secret for CosmosDB
      run: |
          kubectl create secret generic cosmosdb-secret \
            --from-literal=cosmosdb_connection_string='${{ secrets.COSMOSDB_CONNECTION_STRING }}' \
            --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to AKS
      run: |
        kubectl apply -f deployment.yaml
        kubectl set image deployment/weatherapi weatherapi=${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER }}/weatherapi:${{ github.sha }}

    - name: Verify Deployment Status
      run: |
          kubectl rollout status deployment/weatherapi
          kubectl get services

  postman-tests:
    runs-on: ubuntu-latest
    needs: build-and-deploy  # Ensures this job runs after build-and-deploy job succeeds

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Newman (Postman CLI)
        run: |
          npm install -g newman

      - name: Run Postman Tests
        run: |
          newman run ./tests/WeatherAPI.postman_collection.json \
            --reporters cli,json
          
      - name: Upload Newman Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman/*.json